<table width="100%">
	<tr>
		<td>
			<div class="lang">
				<?php 					
					if ($_SESSION["lang"] == "ua"){ ?>
						<a href="system/length.php"><img src="images/en.png" width="30" height="16" class="img_lang"></a>						
					<?php }else{ ?>
						<a href="system/length.php"><img src="system/img_len.php" class="img_lang"></a>
					<?php }					
				?>				
				<p align="center"><img src="images/web.png" width="128" height="128" class="header"></p>
			</div>
		</td>
	</tr>
</table>